# 项目相关配置
project:
  name: smartLearning  # 名称
  version: 1.0.0   # 版本
  copyrightYear: 2021   # 版权年份
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: D:/uploadPath
  addressEnabled: false   # 获取ip地址开关
  captchaType: math   # 验证码类型 math 数组计算 char 字符验证
  captchaExpiration: 10   # 验证码有效期/分钟
  # 上传基本路径
  upload: ${project.profile}/upload
  # 下载基本路径
  download: ${project.profile}/download
server:
  port: 9090
spring:
  mvc:
    #静态资源映射访问路径
    static-path-pattern: /**
  resources:
  #静态资源所在目录
#    static-locations: file:D://uploadPath/upload,
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test9527?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # mail 发邮件
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com  #163邮箱 smtp.163.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: wengaoxue@163.com
#    username: 442872071@qq.com
    #163邮箱授权码
    password: RBDHRZBAPPHCMDHE
#    password: qemdtpralchdcage
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  # 包扫描 多个以，隔开
  type-aliases-package: com.example.demo.**.vo,com.example.demo.**.entity
  global-config: #主键自增
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: -1 # 逻辑已删除值(默认为 -1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    cache-enabled: true # 开启二级缓存

# 日志配置
logging:
  config: classpath:logback-spring-dev.xml
  level:
    com.ycspace.smartlearning: debug
    org.springframework: info